defaults: 
   speed: 1
   process-time: 60
   prodution: 24
   consumption: 16
   inventory-title: "&8机器面板"

machines: 

   ENDLESS_GENERATOR: 

      prodution: 1024
      # Energy to generate per sec and per redstone power
      
   NETHER_STAR_GENERATOR: 
      
      speed: 1