main: io.freeze_dolphin.ultimate_generators.PlugGividado
version: ${project.version}

name: UltimateGenerators
author: Freeze_Dolphin

website: https://github.com/freeze-dolphin/UltimateGenerators/

depend:
  - Slimefun
  - CS-CoreLib
