name: UltimateGenerators
main: io.freeze_dolphin.ultimate_generators.Loader
version: ${project.version}
author: Freeze_Dolphin

depend: [Slimefun, CS-CoreLib]



# ----------------------------
# Internal Configurations
# ----------------------------

show-machine-indicator: true # Default: true
# Whether to show the machine status indicator in machines' GUI
