name: UltimateGenerators
main: io.freeze_dolphin.ultimate_generators.Loader
version: ${project.version}
author: Freeze_Dolphin
website: https://github.com/freeze-dolphin/UltimateGenerators/

depend: [Slimefun, CS-CoreLib]
